version: "3.8"

services:

  activemq:
    image: vromero/activemq-artemis:2.14.0
    ports:
      - "8161:8161"
      - "61616:61616"

  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mssc-mysql-data:/var/lib/mysql

  mysql-adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8090:8080

volumes:
  mssc-mysql-data:
